### ISSUE TITLE
create a new branch for bgc

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/make_diag_table#2]
Hi @aekiss,

I'm starting to create a new branch for `make_diag_table` to add BGC diags. As shown below, I think you have already started and may have added all in the past, but I will try to update the repository based on this. Let me know if you have any advice.

=======================

I've set up one-field-per-file BGC outputs - see `diag_table*` in https://github.com/COSIMA/1deg_jra55_iaf/tree/bgc-mdppm-run/ocean and the output files in `/scratch/v45/aek156/access-om2/archive/1deg_iamip_test_mdppm/output003/ocean/*bgc*` - does that look OK to you?

_Originally posted by @aekiss in https://github.com/COSIMA/1deg_jra55_iaf/issues/11#issuecomment-847435573_

**Comment by hakaseh** [comment]
@aekiss
i should add all the bgc diagnostics in `diag_table_source.yaml` and that's probably all I need to do, correct?
given that this is the default setup, i'll try to choose a temporal resolution reasonable for each diagnostic.

**Comment by hakaseh** [comment]
another question. would you prefer to have a separate branch like `master+bgc` for `make_diag_table` too? If bgc diags are listed in `diag_table` but the model is physics-only, it will only give warning and won't force stop the run, but this will give a long list of warnings in `access-om2.[err,out]`. let me know if you prefer a separate branch.

**Comment by hakaseh** [comment]
could you give me a permission to create a remote branch `master+bgc`? I got the following error:

```
(base) [hh0162@gadi-login-07 make_diag_table]$ git push origin bgc-dev-hh:master+bgc
Username for 'https://github.com': hakaseh
Password for 'https://hakaseh@github.com': 
remote: Permission to COSIMA/make_diag_table.git denied to hakaseh.
fatal: unable to access 'https://github.com/COSIMA/make_diag_table.git/': The requested URL returned error: 403
```

My next step is to create a control directory for `master+bgc` and run the 1-deg model for a year with the updated `diag_table`.

**Comment by aekiss** [comment]
Hi @hakase, sorry, I only just saw this. I don't really think it's necessary to put the bgc stuff in this `make_diag_table` repo, as it only contains an example `diag_table_source.yaml` that is not actually used in configurations.
