### ISSUE TITLE
created 3 branches for Cycle 4

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/make_diag_table#3]
@aekiss I created three branches for Cycle 4 in my fork repo:

https://github.com/hakaseh/make_diag_table/tree/cycle4_1958-1978
https://github.com/hakaseh/make_diag_table/tree/cycle4_1979-2015
https://github.com/hakaseh/make_diag_table/tree/cycle4_2016-2018

Three branches because BGC diagnostics will differ in three periods. The first period (1958-1978) is spin-up, so the least number of diagnostics. The last period (2016-2018) includes 6-hourly output for animations as discussed previously with the group. The diagnostics for physics are identical to https://github.com/COSIMA/01deg_jra55_iaf/tree/01deg_jra55v140_iaf_cycle4 among the three branches.

**Comment by aekiss** [comment]
Hi @hakase thanks for doing these. 

In practice you'd need to manually stop the cycle 4 experiment to change the diag_table, and this change will be recorded in in the experiment's commit history. But maybe it will prove to be helpful to have them here too, so you can add these branches here if you like (despite what I said [here](https://github.com/COSIMA/make_diag_table/issues/2#issuecomment-965857468)).

I've now given you access to push these branches.

**Comment by hakaseh** [comment]
thanks @aekiss . i pushed all 3 branches, as well as `master+bgc`, which contains all of the available BGC diagnostics. this branch can act as a reference to all of the available BGC diagnostics for WOMBAT. not all diagnostics are listed in any of the control directories (e.g. https://github.com/COSIMA/01deg_jra55_iaf/tree/master+bgc) so i think it's a good idea to have a full list here.
