### ISSUE TITLE
error when executed as job on Gadi

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/make_diag_table#4]
To implement this (https://github.com/COSIMA/access-om2/issues/241), I execute `make_diag_table.py` at the beginning of each run defined in `config.yaml` (https://github.com/COSIMA/access-om2/issues/241#issuecomment-982092756). However, I get the following error and `make_diag_table.py` is not executed during the run:

```
=== ERROR ===
The use of the #!/usr/bin/env python interpreter line in python scripts
has been deprecated.

Please modify this script:
/scratch/v45/hh0162/access-om2-cycle4/control/test_1deg_jra55_iamip2_exc/ocean/make_diag_table.py

To use either #!/usr/bin/env python3 or #!/usr/bin/env python2
depending on which version of python you require
Alternatively, if you are unable to modify this script
You can load the python2-as-python or python3-as-python
modules depending on which version of python you require
Currently Loaded Modulefiles:
 1) openmpi/4.1.2(default)   2) pbs
```
I suggest to add `3` at the end of `#!/usr/bin/env python`.

**Comment by aekiss** [comment]
Does it run if you use `#!/usr/bin/env python3` ?

**Comment by hakaseh** [comment]
yes it does.

**Comment by aekiss** [comment]
Closing - I've fixed this everywhere I can think of
