### ISSUE TITLE
MOM6 compatibility

### ISSUE THREAD

**Issue by aekiss** [COSIMA/make_diag_table#5]
Should check whether this is compatible with MOM6 and update if needed.

**Comment by angus-g** [comment]
FMS can actually support a YAML diag table natively: https://github.com/NOAA-GFDL/FMS/blob/main/diag_manager/diag_yaml_format.md

Other than that , I think the old format is the same between MOM5 and MOM6, since it comes from FMS and not the models themselves.

**Comment by aekiss** [comment]
Thanks @angus-g!

**Comment by aekiss** [comment]
The `make_diag_table` YAML format is designed to minimise repetition and facilitate automatic construction of meaningful filenames, e.g. to support one file per variable. The FMS YAML format seems to be designed with different objectives.

**Comment by aekiss** [comment]
I can confirm what @angus-g suspected: `diag_table` generated by `make_diag_table.py` worked fine in a test run with ACCESS-OM3, so it looks like it's already compatible with MOM6.

**Comment by aekiss** [comment]
Of course, while `make_diag_table.py` is general enough to handle MOM6, `diag_table_source.yaml` would need to be changed to account for the differing variable names and vertical remapping - see https://mom6.readthedocs.io/en/main/api/generated/pages/Diagnostics.html#native-diagnostics
